spring:
  application:
    name: bluebank-api
  datasource:
    url: jdbc:postgresql://localhost:5433/bluebank-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: GMT+0