name: BlueBank CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build, test and code quality
        run: mvn clean verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: bluebank-jar
          path: target/*.jar

  docker-image-build-push:
    needs: build-test-quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: bluebank-jar
          path: target

      - name: Build Docker image
        run: docker build -t bluebank-api .

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u migstreva --password-stdin

      - name: Tag Docker image
        run: docker tag bluebank-api ghcr.io/migstreva/bluebank-api:latest

      - name: Push Docker image
        run: docker push ghcr.io/migstreva/bluebank-api:latest